name: Update Docker Hub Description

on:
  push:
    branches:
      - simple
    paths:
      - README.md
      - .github/workflows/update-docker-overview.yml

jobs:
  dockerHubDescription:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Docker Hub Description
      uses: peter-evans/dockerhub-description@v3
      with:
        username: ${{ secrets.DOCKER_HUB_USERNAME }}
        password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}
        repository: buildwithdan/flask-portfolio
        short-description: ${{ github.event.repository.description }}
        enable-url-completion: true
